/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2016-12-06 05:50:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddNewBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/Users/ruchit/Documents/CMPE275/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/spring-webmvc-4.0.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1404790198000L));
    _jspx_dependants.put("jar:file:/Users/ruchit/Documents/CMPE275/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/spring-webmvc-4.0.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1404790198000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480658872000L));
    _jspx_dependants.put("jar:file:/Users/ruchit/Documents/CMPE275/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.6.RELEASE.jar", Long.valueOf(1480658870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${temp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.10.2.js\"\n");
      out.write("\t\t\ttype=\"text/javascript\"></script>\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t@import \"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\";\n");
      out.write("\t\t@import \"https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\";\n");
      out.write("\t\t</style>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<title></title>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t    <div class=\"container\">\n");
      out.write("        \t<div class=\"row\">\n");
      out.write("        \t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("        \n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("            \t<h4 style=\"color:white; padding-top:6px; padding-left:20px;\">Library Management System</h4>\n");
      out.write("            \t\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse pull-right\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Profile</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Signout</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("    </nav>\n");
      out.write("    </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("        <div class=\"col-md-3\">\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("        <!-- Sidebar -->\n");
      out.write("        <div id=\"sidebar-wrapper\">\n");
      out.write("            <ul class=\"sidebar-nav\">\n");
      out.write("                <li class=\"sidebar-brand\">\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        Start Bootstrap\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">Dashboard</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">Search Book</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">Add Book</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">Delete Book</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">Profile</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">Sign Out</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- /#sidebar-wrapper -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /#wrapper -->\n");
      out.write("</div>\n");
      out.write("\t\t\n");
      out.write("            <div class=\"col-md-7\"  style=\"padding-top:120px;\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("            <div class=\"col-md-1\"></div>\n");
      out.write("                <div class=\"panel panel-default\">\n");
      out.write("                    <div class=\"panel-heading\">\n");
      out.write("                        <h3 style=\"text-align:center\">Search Book Here</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"panel-body\">\n");
      out.write("                        <form action='/LibrarySystem/searchBookDetail' method=\"post\" class=\"form-horizontal\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                            \t<div class=\"col-md-1\"></div>\n");
      out.write("                            \t<div class=\"col-md-10\">\n");
      out.write("                            \t\t<label for=\"ex1\">Search Book By ISBN: </label>\n");
      out.write("\t\t\t\t\t\t\t  \t\t<input class=\"form-control\" type=\"text\" id=\"isbn\" name=\"isbn\" placeholder=\"Enter ISBN here\" required />\n");
      out.write("\t\t\t\t\t\t\t  \t\t<input type=\"hidden\" name=\"isbnData\" id=\"isbnData\">\n");
      out.write("                            \t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<br>\n");
      out.write("                            <div style=\"padding-left:40%\">\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary\" id=\"getData\">Search Book</button>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                 </div>\n");
      out.write("                 </div>\n");
      out.write("                 <div class=\"row\">\n");
      out.write("                 <div id=\"tab\" hidden=\"true\">\n");
      out.write("                  <table class=\"table\" border=2px id=\"tab1\">\n");
      out.write("             <thead>\n");
      out.write("             \t<th>Author</th>\n");
      out.write("             \t<th>Title</th>\n");
      out.write("             \t<th>Call Number</th>\n");
      out.write("             \t<th>Publisher</th>\n");
      out.write("             \t<th>Year of Publication</th>\n");
      out.write("             \t<th>Cover Image</th>\n");
      out.write("             </thead>\n");
      out.write("             <tr>\n");
      out.write("             \t\n");
      out.write("             </tr>\n");
      out.write("          \t\t</table>\n");
      out.write("         \t\t</div>\n");
      out.write("         \t\t<div class=\"col-md-1\"></div>\n");
      out.write("           </div>\n");
      out.write("           </div>  \n");
      out.write("           <div class=\"col-md-1\"></div>          \n");
      out.write("       </div>\n");
      out.write("       <div class=\"row\"> \n");
      out.write("       \t\t<div class=\"col-md-2\"></div>\n");
      out.write("       \t\t<div class=\"col-md-7\">\n");
      out.write("             <form id=\"form1\" hidden=true;>\n");
      out.write("\t            <div class=\"row\">\n");
      out.write("\t            \t<div class=\"col-md-4\"></div>\n");
      out.write("\t            \t<div class=\"col-md-4\">\n");
      out.write("\t            \t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t    <label>Number Of Copies</label>\n");
      out.write("\t\t\t\t\t    <input type=\"number\" class=\"form-control\" name=\"numberOfCopies\" placeholder=\"Enter Number Of Copies\">\n");
      out.write("\t\t\t\t\t  </div>\n");
      out.write("\t            \t</div>\n");
      out.write("\t            \t<div class=\"col-md-4\">\n");
      out.write("\t            \t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t    <label>Location In Library</label>\n");
      out.write("\t\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"location\" placeholder=\"Enter Location In Library\">\n");
      out.write("\t\t\t\t\t  </div>\n");
      out.write("\t            \t</div>\n");
      out.write("\t            \t\n");
      out.write("\t            </div><br>\n");
      out.write("\t            <div class=\"row\">\n");
      out.write("\t\t            <div style=\"padding-left:365px;\">\n");
      out.write("\t\t            \t<input type=\"submit\" class=\"btn btn-primary\" value=\"Add Book to Library\">\n");
      out.write("\t\t            </div>\n");
      out.write("\t            </div>\n");
      out.write("            </form>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"col-md-1\"></div>\n");
      out.write("         </div>\n");
      out.write("                \t\t\n");
      out.write("\t\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>  \n");
      out.write("\t</body>\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t$(\"#getData\").click(function(){\n");
      out.write("\t\t\tvar isbnVal = document.getElementById('isbn').value;\n");
      out.write("\t\t\talert(\"isbnVal: \"+isbnVal);\n");
      out.write("\t\t\tvar url = \"https://www.googleapis.com/books/v1/volumes?q=isbn:8179923274\";\n");
      out.write("\t\t\talert(url)\n");
      out.write("\t        $.get(url, function(data, status){\n");
      out.write("\t            alert(\"Data: \" + JSON.stringify(data, null, 2) + \"\\nStatus: \" + status);\n");
      out.write("\t\t\t\tdocument.getElementById(\"getData\").value = data;\n");
      out.write("\t\t\t\t//alert(\"getData: \"+document.getElementById(\"getData\").value);\n");
      out.write("\t\t\t\tdocument.getElementById(\"tab\").hidden=false;\n");
      out.write("\t\t\t\tdocument.getElementById(\"form1\").hidden=false;\n");
      out.write("\t            data1 = data;\n");
      out.write("\t\t\t var table = document.getElementById(\"tab1\");\n");
      out.write("\t\t\t    var row = table.insertRow(-1);\n");
      out.write("\t\t\t    var cell1 = row.insertCell(0);\n");
      out.write("\t\t\t    var cell2 = row.insertCell(1);\n");
      out.write("\t\t\t    var cell3 = row.insertCell(2);\n");
      out.write("\t\t\t    var cell4 = row.insertCell(3);\n");
      out.write("\t\t\t    var cell5 = row.insertCell(4);\n");
      out.write("\t\t\t    var cell6 = row.insertCell(5);\n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    cell1.innerHTML = data.items[0].volumeInfo.authors.toString();\n");
      out.write("\t    cell2.innerHTML = data.items[0].volumeInfo.title;\n");
      out.write("\t    cell3.innerHTML = data.items[0].volumeInfo.publisher;\n");
      out.write("\t    cell4.innerHTML = data.items[0].volumeInfo.publisher;\n");
      out.write("\t    cell5.innerHTML = data.items[0].volumeInfo.publishedDate;\n");
      out.write("\t    cell6.innerHTML = data.items[0].volumeInfo.imageLinks.thumbnail;\n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t            /* alert(data.items[0].id);\n");
      out.write("\t            alert(data.items[0].volumeInfo.title);\n");
      out.write("\t            alert(data.items[0].volumeInfo.authors.toString());\n");
      out.write("\t            alert(data.items[0].volumeInfo.publisher);\n");
      out.write("\t            alert(data.items[0].volumeInfo.publishedDate);\n");
      out.write("\t            alert(data.items[0].volumeInfo.imageLinks.thumbnail);\n");
      out.write("\t            alert(data.items[0].volumeInfo.categories.toString()); */\n");
      out.write("\t        });\n");
      out.write("\t    });\n");
      out.write("\t\n");
      out.write("\t</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /WEB-INF/views/AddNewBook.jsp(7,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/resources/temp.css");
      // /WEB-INF/views/AddNewBook.jsp(7,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("temp");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
    }
    return false;
  }
}
