/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2016-12-06 03:55:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/Users/ruchit/Documents/CMPE275/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/spring-webmvc-4.0.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1404790198000L));
    _jspx_dependants.put("jar:file:/Users/ruchit/Documents/CMPE275/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/spring-webmvc-4.0.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1404790198000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480658872000L));
    _jspx_dependants.put("jar:file:/Users/ruchit/Documents/CMPE275/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibrarySystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.6.RELEASE.jar", Long.valueOf(1480658870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <title>themeinthebox.com</title>\n");
      out.write("\t<!-- core CSS -->\n");
      out.write("\t");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bootstrap}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${font}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${animate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("     ");
      if (_jspx_meth_spring_005furl_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carousel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${transition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prettyPhoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${responsive}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\n");
      out.write("    <![endif]-->       \n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("</head><!--/head-->\n");
      out.write("\n");
      out.write("<body id=\"home\" class=\"homepage\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <header id=\"top-header\" class=\"navbar-inverse navbar-fixed-top\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <!-- responsive nav button -->\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <!-- /responsive nav button -->\n");
      out.write("                    \n");
      out.write("                    <!-- logo -->\n");
      out.write("                    <!-- <div class=\"navbar-brand\">\n");
      out.write("                        <a class=\"smooth-scroll\" data-section=\"#home\" href=\"#home\" >\n");
      out.write("                            <img src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        </a>\n");
      out.write("                    </div> -->\n");
      out.write("                    <!-- /logo -->\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- main nav -->\n");
      out.write("                <nav class=\"collapse navbar-collapse navbar-right\" role=\"navigation\">\n");
      out.write("                    <div class=\"main-menu\">\n");
      out.write("                        <ul id=\"nav\" class=\"nav navbar-nav\">\n");
      out.write("                            <li class=\"scroll\"><a href=\"#home\" data-section=\"#home\">Home</a></li>\n");
      out.write("                            <li class=\"scroll\"><a href=\"#about\" data-section=\"#about\">About</a></li>\n");
      out.write("                            <li class=\"scroll\"><a href=\"#services\" data-section=\"#services\">Services</a></li>\n");
      out.write("                            <li class=\"scroll\"><a href=\"#portfolio\" data-section=\"#portfolio\">Portfolio</a></li>\n");
      out.write("                            <li class=\"scroll\"><a href=\"#contact-area\" data-section=\"#contact-area\">Contact</a></li>\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/registration\">SignUp</a>\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/login\">LogIn</a>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("                <!-- /main nav -->\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("    <section id=\"main-slider\">\n");
      out.write("        <div class=\"owl-carousel\">\n");
      out.write("            <div class=\"item\" style=\"background-image: url(https://i.ytimg.com/vi/hDWbxhiSQ20/maxresdefault.jpg);\">\n");
      out.write("                <div class=\"slider-inner\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-12\">\n");
      out.write("                                <div class=\"carousel-content text-center\">\n");
      out.write("                                    <h2>I have always imagined that Paradise will be a kind of library <span>Color</span>.</h2>\n");
      out.write("                                    <p>Any book that helps a child to form a habit of reading, to make reading one of his deep and continuing needs, is good for him.</p>\n");
      out.write("                                    <a class=\"btn btn-primary btn-lg\" href=\"#\">Read More</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div><!--/.item-->\n");
      out.write("            <div class=\"item\" style=\"background-image: url(https://images7.alphacoders.com/697/697523.jpg);\">\n");
      out.write("                <div class=\"slider-inner\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-12\">\n");
      out.write("                                <div class=\"carousel-content text-center\">\n");
      out.write("\n");
      out.write("                                    <h2>OUR MAIN GOAL IS CONTINUOUSLY SATISFY OUR <span>Clients</span></h2>\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et  dolore magna incididunt ut labore aliqua. </p>\n");
      out.write("                                    <a class=\"btn btn-primary btn-lg\" href=\"#\">Read More</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div><!--/.item-->\n");
      out.write("            <div class=\"item\" style=\"background-image: url(http://blog.hdwallsource.com/wp-content/uploads/2016/03/girl-in-library-wallpaper-44311-45430-hd-wallpapers.jpg);\">\n");
      out.write("                <div class=\"slider-inner\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-12\">\n");
      out.write("                                <div class=\"carousel-content text-center\">\n");
      out.write("                                    <h2>Accessible design is good design. Only with <span>Color</span>.</h2>\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et  dolore magna incididunt ut labore aliqua. </p>\n");
      out.write("                                    <a class=\"btn btn-primary btn-lg\" href=\"#\">Read More</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div><!--/.item-->\n");
      out.write("            \n");
      out.write("        </div><!--/.owl-carousel-->\n");
      out.write("    </section><!--/#main-slider-->\n");
      out.write("\n");
      out.write("    <section id=\"about\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("\n");
      out.write("            <div class=\"section-header\">\n");
      out.write("                <h2 class=\"section-title text-center wow fadeInDown\">WELCOME TO OUR COMPANY</h2>\n");
      out.write("                <p class=\"text-center wow fadeInDown\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                \n");
      out.write("\n");
      out.write("                <div class=\"col-sm-6 wow fadeInRight\">\n");
      out.write("                    <h3 class=\"column-title\">A Little More About Us</h3>\n");
      out.write("                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>\n");
      out.write("\n");
      out.write("                    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>\n");
      out.write("\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"#\">Discover Us</a>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-sm-6 wow fadeInLeft\">\n");
      out.write("                    <img class=\"img-responsive\" src=\"https://static.pexels.com/photos/8700/wall-animal-dog-pet.jpg\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section><!--/#about-->\n");
      out.write("\n");
      out.write("    <section id=\"services\" >\n");
      out.write("        <div class=\"container\">\n");
      out.write("\n");
      out.write("            <div class=\"section-header\">\n");
      out.write("                <h2 class=\"section-title text-center wow fadeInDown\">Our Services</h2>\n");
      out.write("                <p class=\"text-center wow fadeInDown\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"features\">\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"0ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-bicycle\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"100ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-cubes\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">SEO Services</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"200ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-connectdevelop\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"300ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa  fa-diamond\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"400ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-user-secret\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"500ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-key\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"600ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-laptop\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-6 col-md-3 col-lg-3 wow fadeInUp\" data-wow-duration=\"300ms\" data-wow-delay=\"700ms\">\n");
      out.write("                        <div class=\"features-item\">\n");
      out.write("                            <div class=\"features-icon\">\n");
      out.write("                                <i class=\"fa fa-paw\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <h3 class=\"features-title font-alt\">Optimised for speed</h3>\n");
      out.write("                            Careful attention to detail and clean, well structured code ensures a smooth user experience for all your visitors.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div><!--/.row-->    \n");
      out.write("        </div><!--/.container-->\n");
      out.write("    </section><!--/#services-->\n");
      out.write("\n");
      out.write("    <section id=\"portfolio\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"section-header\">\n");
      out.write("                <h2 class=\"section-title text-center wow fadeInDown\">Our Works</h2>\n");
      out.write("                <p class=\"text-center wow fadeInDown\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"text-center\">\n");
      out.write("                <ul class=\"portfolio-filter\">\n");
      out.write("                    <li><a class=\"active\" href=\"#\" data-filter=\"*\">All Works</a></li>\n");
      out.write("                    <li><a href=\"#\" data-filter=\".animation\">Animation</a></li>\n");
      out.write("                    <li><a href=\"#\" data-filter=\".Business\">Business</a></li>\n");
      out.write("                    <li><a href=\"#\" data-filter=\".art\">Art</a></li>\n");
      out.write("                </ul><!--/#portfolio-filter-->\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"portfolio-items\">\n");
      out.write("                <div class=\"portfolio-item animation\">\n");
      out.write("                    <div class=\"portfolio-item-inner\">\n");
      out.write("                        <img class=\"img-responsive\" src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"portfolio-info\">\n");
      out.write("                            <h3>Portfolio Item 1</h3>\n");
      out.write("                            <a class=\"preview\" href=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" rel=\"prettyPhoto\">\n");
      out.write("                                <img src=\"images/portfolio/expand.png\" alt=\"\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div><!--/.portfolio-item-->\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"portfolio-item Business art\">\n");
      out.write("                    <div class=\"portfolio-item-inner\">\n");
      out.write("                        <img class=\"img-responsive\" src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"portfolio-info\">\n");
      out.write("                            <h3>Portfolio Item 2</h3>\n");
      out.write("                            <a class=\"preview\" href=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpgg\" rel=\"prettyPhoto\">\n");
      out.write("                                <img src=\"images/portfolio/expand.png\" alt=\"\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div><!--/.portfolio-item-->\n");
      out.write("\n");
      out.write("                <div class=\"portfolio-item animation\">\n");
      out.write("                    <div class=\"portfolio-item-inner\">\n");
      out.write("                        <img class=\"img-responsive\" src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"portfolio-info\">\n");
      out.write("                            <h3>Portfolio Item 3</h3>\n");
      out.write("                            <a class=\"preview\" href=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" rel=\"prettyPhoto\">\n");
      out.write("                                <img src=\"images/portfolio/expand.png\" alt=\"\">\n");
      out.write("\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div><!--/.portfolio-item-->\n");
      out.write("\n");
      out.write("                <div class=\"portfolio-item Business\">\n");
      out.write("                    <div class=\"portfolio-item-inner\">\n");
      out.write("                        <img class=\"img-responsive\" src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"portfolio-info\">\n");
      out.write("                            <h3>Portfolio Item 5</h3>\n");
      out.write("                            <a class=\"preview\" href=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" rel=\"prettyPhoto\">\n");
      out.write("                                <img src=\"images/portfolio/expand.png\" alt=\"\">\n");
      out.write("\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div><!--/.portfolio-item-->\n");
      out.write("\n");
      out.write("                <div class=\"portfolio-item animation art\">\n");
      out.write("                    <div class=\"portfolio-item-inner\">\n");
      out.write("                        <img class=\"img-responsive\" src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"portfolio-info\">\n");
      out.write("                            <h3>Portfolio Item 7</h3>\n");
      out.write("                            <a class=\"preview\" href=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" rel=\"prettyPhoto\">\n");
      out.write("                                <img src=\"images/portfolio/expand.png\" alt=\"\">\n");
      out.write("\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div><!--/.portfolio-item-->\n");
      out.write("\n");
      out.write("                <div class=\"portfolio-item Business\">\n");
      out.write("                    <div class=\"portfolio-item-inner\">\n");
      out.write("                        <img class=\"img-responsive\" src=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"portfolio-info\">\n");
      out.write("                            <h3>Portfolio Item 8</h3>\n");
      out.write("                            <a class=\"preview\" href=\"http://www.planwallpaper.com/static/images/stunning-images-of-the-space.jpg\" rel=\"prettyPhoto\">\n");
      out.write("                                <img src=\"images/portfolio/expand.png\" alt=\"\">\n");
      out.write("\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div><!--/.portfolio-item-->\n");
      out.write("            </div>\n");
      out.write("        </div><!--/.container-->\n");
      out.write("    </section><!--/#portfolio-->\n");
      out.write("\n");
      out.write("    <section id=\"contact-area\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"section-header\">\n");
      out.write("                    <h2 class=\"section-title text-center wow fadeInDown animated\" style=\"visibility: visible;\">Send Message</h2>\n");
      out.write("                    <p class=\"text-center wow fadeInDown animated\" style=\"visibility: visible;\">Drop a line to us. Your word is most important to us.</p>\n");
      out.write("                </div>\n");
      out.write("                <form id=\"main-contact-form\" name=\"contact-form\" method=\"post\" action=\"#\">\n");
      out.write("                    <div class=\"col-lg-6 animated animate-from-left\" style=\"opacity: 1; left: 0px;\">\n");
      out.write("\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                                <label for=\"name\">Your Name (Required)</label>\n");
      out.write("                                <input id=\"name\" type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"Name\" required>\n");
      out.write("                            </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                                <label for=\"email\">Email Address</label>\n");
      out.write("                                <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Email\" required>\n");
      out.write("                            </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"subject\">Subject</label>\n");
      out.write("                            <input type=\"text\" id=\"subject\" name=\"subject\" class=\"form-control\" placeholder=\"Subject\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-6 animated animate-from-right\" style=\"opacity: 1; right: 0px;\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"message\">Your Message</label>\n");
      out.write("                            <textarea name=\"message\" id=\"message\" class=\"form-control\" rows=\"8\" placeholder=\"Message\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("                    <div class=\"text-center\">\n");
      out.write("\n");
      out.write("                          <button type=\"submit\" class=\"btn btn-primary btn-lg btn-send-msg\">Send Message</button>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section><!--/#bottom-->\n");
      out.write("\n");
      out.write("    <footer id=\"footer\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-sm-12\">\n");
      out.write("                    <p class=\"text-center\">\n");
      out.write("                        @2017 Library Management System\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer><!--/#footer-->\n");
      out.write("\t");
      if (_jspx_meth_spring_005furl_005f8(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jqueryJs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("\t");
      if (_jspx_meth_spring_005furl_005f9(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bootstrap}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/jquery.js\"></script> -->\n");
      out.write("    <!-- <script src=\"js/bootstrap.min.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f10(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carousel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/owl.carousel.min.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f11(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mousescroll}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/mousescroll.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f12(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prettyPhoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/jquery.prettyPhoto.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f13(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isotope}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/jquery.isotope.min.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f14(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inview}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/jquery.inview.min.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f15(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wow}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/wow.min.js\"></script> -->\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f16(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${main}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\n");
      out.write("    <!-- <script src=\"js/main.js\"></script> -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /WEB-INF/views/welcome.jsp(13,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/resources/css/bootstrap.min.css");
      // /WEB-INF/views/welcome.jsp(13,1) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("bootstrap");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f1.setParent(null);
      // /WEB-INF/views/welcome.jsp(16,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setValue("/resources/css/font-awesome.min.css");
      // /WEB-INF/views/welcome.jsp(16,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setVar("font");
      int[] _jspx_push_body_count_spring_005furl_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
        if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f2 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f2.setParent(null);
      // /WEB-INF/views/welcome.jsp(19,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f2.setValue("/resources/css/animate.min.css");
      // /WEB-INF/views/welcome.jsp(19,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f2.setVar("animate");
      int[] _jspx_push_body_count_spring_005furl_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f2 = _jspx_th_spring_005furl_005f2.doStartTag();
        if (_jspx_th_spring_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f3 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f3.setParent(null);
      // /WEB-INF/views/welcome.jsp(22,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f3.setValue("/resources/css/owl.carousel.css");
      // /WEB-INF/views/welcome.jsp(22,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f3.setVar("carousel");
      int[] _jspx_push_body_count_spring_005furl_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f3 = _jspx_th_spring_005furl_005f3.doStartTag();
        if (_jspx_th_spring_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f4 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f4.setParent(null);
      // /WEB-INF/views/welcome.jsp(25,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f4.setValue("/resources/css/owl.transitions.css");
      // /WEB-INF/views/welcome.jsp(25,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f4.setVar("transition");
      int[] _jspx_push_body_count_spring_005furl_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f4 = _jspx_th_spring_005furl_005f4.doStartTag();
        if (_jspx_th_spring_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f4.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f5 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f5.setParent(null);
      // /WEB-INF/views/welcome.jsp(28,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f5.setValue("/resources/css/prettyPhoto.css");
      // /WEB-INF/views/welcome.jsp(28,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f5.setVar("prettyPhoto");
      int[] _jspx_push_body_count_spring_005furl_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f5 = _jspx_th_spring_005furl_005f5.doStartTag();
        if (_jspx_th_spring_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f5.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f6 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f6.setParent(null);
      // /WEB-INF/views/welcome.jsp(31,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f6.setValue("/resources/css/main.css");
      // /WEB-INF/views/welcome.jsp(31,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f6.setVar("main");
      int[] _jspx_push_body_count_spring_005furl_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f6 = _jspx_th_spring_005furl_005f6.doStartTag();
        if (_jspx_th_spring_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f6.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f7 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f7.setParent(null);
      // /WEB-INF/views/welcome.jsp(34,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f7.setValue("/resources/css/responsive.css");
      // /WEB-INF/views/welcome.jsp(34,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f7.setVar("responsive");
      int[] _jspx_push_body_count_spring_005furl_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f7 = _jspx_th_spring_005furl_005f7.doStartTag();
        if (_jspx_th_spring_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f7.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f8 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f8.setParent(null);
      // /WEB-INF/views/welcome.jsp(416,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f8.setValue("/resources/js/jquery.js");
      // /WEB-INF/views/welcome.jsp(416,1) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f8.setVar("jqueryJs");
      int[] _jspx_push_body_count_spring_005furl_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f8 = _jspx_th_spring_005furl_005f8.doStartTag();
        if (_jspx_th_spring_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f8.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f9 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f9.setParent(null);
      // /WEB-INF/views/welcome.jsp(418,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f9.setValue("/resources/js/bootstrap.min.js");
      // /WEB-INF/views/welcome.jsp(418,1) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f9.setVar("bootstrap");
      int[] _jspx_push_body_count_spring_005furl_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f9 = _jspx_th_spring_005furl_005f9.doStartTag();
        if (_jspx_th_spring_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f9.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f10 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f10.setParent(null);
      // /WEB-INF/views/welcome.jsp(422,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f10.setValue("/resources/js/owl.carousel.min.js");
      // /WEB-INF/views/welcome.jsp(422,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f10.setVar("carousel");
      int[] _jspx_push_body_count_spring_005furl_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f10 = _jspx_th_spring_005furl_005f10.doStartTag();
        if (_jspx_th_spring_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f10.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f10);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f11 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f11.setParent(null);
      // /WEB-INF/views/welcome.jsp(425,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f11.setValue("/resources/js/mousescroll.js");
      // /WEB-INF/views/welcome.jsp(425,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f11.setVar("mousescroll");
      int[] _jspx_push_body_count_spring_005furl_005f11 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f11 = _jspx_th_spring_005furl_005f11.doStartTag();
        if (_jspx_th_spring_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f11[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f11.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f11.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f11);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f12 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f12.setParent(null);
      // /WEB-INF/views/welcome.jsp(428,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f12.setValue("/resources/js/jquery.prettyPhoto.js");
      // /WEB-INF/views/welcome.jsp(428,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f12.setVar("prettyPhoto");
      int[] _jspx_push_body_count_spring_005furl_005f12 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f12 = _jspx_th_spring_005furl_005f12.doStartTag();
        if (_jspx_th_spring_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f12[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f12.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f12.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f12);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f13 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f13.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f13.setParent(null);
      // /WEB-INF/views/welcome.jsp(431,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f13.setValue("/resources/js/jquery.isotope.min.js");
      // /WEB-INF/views/welcome.jsp(431,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f13.setVar("isotope");
      int[] _jspx_push_body_count_spring_005furl_005f13 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f13 = _jspx_th_spring_005furl_005f13.doStartTag();
        if (_jspx_th_spring_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f13[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f13.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f13.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f13);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f14 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f14.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f14.setParent(null);
      // /WEB-INF/views/welcome.jsp(434,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f14.setValue("/resources/js/jquery.inview.min.js");
      // /WEB-INF/views/welcome.jsp(434,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f14.setVar("inview");
      int[] _jspx_push_body_count_spring_005furl_005f14 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f14 = _jspx_th_spring_005furl_005f14.doStartTag();
        if (_jspx_th_spring_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f14[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f14.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f14.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f14);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f15 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f15.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f15.setParent(null);
      // /WEB-INF/views/welcome.jsp(437,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f15.setValue("/resources/js/wow.min.js");
      // /WEB-INF/views/welcome.jsp(437,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f15.setVar("wow");
      int[] _jspx_push_body_count_spring_005furl_005f15 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f15 = _jspx_th_spring_005furl_005f15.doStartTag();
        if (_jspx_th_spring_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f15[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f15.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f15.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f15);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f16 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    try {
      _jspx_th_spring_005furl_005f16.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f16.setParent(null);
      // /WEB-INF/views/welcome.jsp(440,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f16.setValue("/resources/js/main.js");
      // /WEB-INF/views/welcome.jsp(440,4) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f16.setVar("main");
      int[] _jspx_push_body_count_spring_005furl_005f16 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f16 = _jspx_th_spring_005furl_005f16.doStartTag();
        if (_jspx_th_spring_005furl_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f16[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f16.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f16.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f16);
    }
    return false;
  }
}
